source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
platform :macos, '10.14'

pod 'Sparkle'

target 'UpDataDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UpDataDemo

end
